### ISSUE TITLE
Scraping takes time

### ISSUE THREAD

**Issue by glane2609** [benyamindsmith/ypscrapeR#1]
https://www.yellowpages.com.au/find/plumbers-gas-fitters/sydney-nsw-2000

So this is my url and it's been an hour , but I'm yet to get an output. Can you help me with it ?

**Comment by benyamindsmith** [comment]
@glane2609 this package (at the time) only works for the US [yellowpages.com](https://www.yellowpages.com).

Its been a few years since I looked at this- so its likely that it doesn't entirely work now, but if you want to make this scraper work for your use case, you will need to adjust the selectors in the source code. 


__Update__

This does not work even for yellowpages.com- but it can be fixed. 

![image](https://user-images.githubusercontent.com/46410142/212906363-443f61bd-2a85-457a-8fca-824994d4d51f.png)

**Comment by glane2609** [comment]
Yeah I understood it later. Thanks, also I realised there's ip address
issue as I'm doing it from India. You can close this.

Regards,
Glane
